version: '3.8'

services:
  document-title-suggester:
    build:
      context: .
      dockerfile: Dockerfile  # Optional: specify if your Dockerfile is not named 'Dockerfile'
    container_name: document-title-suggester
    env_file:
      config.env
    volumes:
      - ./config:/app/config
      - ./scripts:/app/scripts
      - ./logs:/app/logs
    #restart: unless-stopped
